name: remote_remote
description: An ofxRemoteParameters client written in Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  osc:
    git: https://github.com/pq/osc.git
  get_ip: ^0.4.0
  wifi: ^0.1.5
  wakelock: ^0.5.0+2
  flutter_focus_watcher:
  flutter_colorpicker:
  logging: ^1.0.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  property_change_notifier:
    git: https://github.com/GauteHaugen/property_change_notifier.git
  page_indicator: ^0.3.0
  xml: ^5.0.2
  flutter_markdown: ^0.6.0
  url_launcher: ^5.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - 'assets/about.md'

publish_to: none
